// TODO BLOCK
export interface Css_Class_Declaration {
	value: string;
}

export const css_classes_by_name: Record<string, Css_Class_Declaration | undefined> = {
	relative: {value: 'position: relative;'},
	absolute: {value: 'position: absolute;'},
	fixed: {value: 'position: fixed;'},
	sticky: {value: 'position: sticky;'},
	static: {value: 'position: static;'},
	overflow_auto: {value: 'overflow: auto;'},
	overflow_hidden: {value: 'overflow: hidden;'},
	overflow_scroll: {value: 'overflow: scroll;'},
	overflow_clip: {value: 'overflow: clip;'},
	overflow_visible: {value: 'overflow: visible;'},
	overflow_x_auto: {value: 'overflow-x: auto;'},
	overflow_x_hidden: {value: 'overflow-x: hidden;'},
	overflow_x_scroll: {value: 'overflow-x: scroll;'},
	overflow_x_clip: {value: 'overflow-x: clip;'},
	overflow_x_visible: {value: 'overflow-x: visible;'},
	overflow_y_auto: {value: 'overflow-y: auto;'},
	overflow_y_hidden: {value: 'overflow-y: hidden;'},
	overflow_y_scroll: {value: 'overflow-y: scroll;'},
	overflow_y_clip: {value: 'overflow-y: clip;'},
	overflow_y_visible: {value: 'overflow-y: visible;'},
	overflow_wrap_anywhere: {value: 'overflow-wrap: anywhere;'},
	overflow_wrap_break_word: {value: 'overflow-wrap: break-word;'},

	/* these include the longhand `display_` because they're less common and would be more ambiguous */
	display_none: {value: 'display: none;'},
	display_contents: {value: 'display: contents;'},
	/* TODO others like `list-item` and `table` variants? after optimizing, sure - https://developer.mozilla.org/en-US/docs/Web/CSS/display */
	inline: {value: 'display: inline;'},
	inline_block: {value: 'display: inline-block;'},
	inline_flex: {value: 'display: inline-flex;'},
	inline_grid: {value: 'display: inline-grid;'},
	block: {value: 'display: block;'},

	/* TODO lots of these, but optimize first? .display_table {
	display: table;
} */
	flex: {value: 'display: flex;'},
	flex_1: {value: 'flex: 1;'},
	flex_wrap: {value: 'flex-wrap: wrap;'},
	flex_wrap_reverse: {value: 'flex-wrap: wrap-reverse;'},
	flex_nowrap: {value: 'flex-wrap: nowrap;'},
	flex_row: {value: 'flex-direction: row;'},
	flex_row_reverse: {value: 'flex-direction: row-reverse;'},
	flex_column: {value: 'flex-direction: column;'},
	flex_column_reverse: {value: 'flex-direction: column-reverse;'},
	grow: {value: 'flex-grow: 1;'},
	grow_0: {value: 'flex-grow: 0;'},
	shrink: {value: 'flex-shrink: 1;'},
	shrink_0: {value: 'flex-shrink: 0;'},

	/* TODO omitting some values, generating on demand will fill in the gaps */
	align_items_center: {value: 'align-items: center;'},
	align_items_start: {value: 'align-items: start;'},
	align_items_end: {value: 'align-items: end;'},
	align_items_baseline: {value: 'align-items: baseline;'},
	align_items_stretch: {value: 'align-items: stretch;'},
	/* TODO omitting some values, generating on demand will fill in the gaps */
	align_content_center: {value: 'align-content: center;'},
	align_content_start: {value: 'align-content: start;'},
	align_content_end: {value: 'align-content: end;'},
	align_content_baseline: {value: 'align-content: baseline;'},
	align_content_space_between: {value: 'align-content: space-between;'},
	align_content_space_around: {value: 'align-content: space-around;'},
	align_content_space_evenly: {value: 'align-content: space-evenly;'},
	align_content_stretch: {value: 'align-content: stretch;'},
	/* TODO omitting some values, generating on demand will fill in the gaps */
	align_self_center: {value: 'align-self: center;'},
	align_self_start: {value: 'align-self: start;'},
	align_self_end: {value: 'align-self: end;'},
	align_self_baseline: {value: 'align-self: baseline;'},
	align_self_stretch: {value: 'align-self: stretch;'},
	/* TODO omitting some values, generating on demand will fill in the gaps */
	justify_content_center: {value: 'justify-content: center;'},
	justify_content_start: {value: 'justify-content: start;'},
	justify_content_end: {value: 'justify-content: end;'},
	justify_content_left: {value: 'justify-content: left;'},
	justify_content_right: {value: 'justify-content: right;'},
	justify_content_space_between: {value: 'justify-content: space-between;'},
	justify_content_space_around: {value: 'justify-content: space-around;'},
	justify_content_space_evenly: {value: 'justify-content: space-evenly;'},
	justify_content_stretch: {value: 'justify-content: stretch;'},
	/* TODO omitting some values, generating on demand will fill in the gaps */
	justify_items_center: {value: 'justify-items: center;'},
	justify_items_start: {value: 'justify-items: start;'},
	justify_items_end: {value: 'justify-items: end;'},
	justify_items_left: {value: 'justify-items: left;'},
	justify_items_right: {value: 'justify-items: right;'},
	justify_items_baseline: {value: 'justify-items: baseline;'},
	justify_items_stretch: {value: 'justify-items: stretch;'},
	/* TODO omitting some values, generating on demand will fill in the gaps */
	justify_self_center: {value: 'justify-self: center;'},
	justify_self_start: {value: 'justify-self: start;'},
	justify_self_end: {value: 'justify-self: end;'},
	justify_self_left: {value: 'justify-self: left;'},
	justify_self_right: {value: 'justify-self: right;'},
	justify_self_baseline: {value: 'justify-self: baseline;'},
	justify_self_stretch: {value: 'justify-self: stretch;'},
	grid: {value: 'display: grid;'},
	float_none: {value: 'float: none;'},
	float_left: {value: 'float: left;'},
	float_right: {value: 'float: right;'},
	float_inline_start: {value: 'float: inline-start;'},
	float_inline_end: {value: 'float: inline-end;'},
	flip_x: {value: 'transform: scaleX(-1);'},
	flip_y: {value: 'transform: scaleY(-1);'},
	flip_xy: {value: 'transform: scaleX(-1) scaleY(-1);'},

	font_sans: {value: 'font-family: var(--font_sans);'},
	font_mono: {value: 'font-family: var(--font_mono);'},
	line_height_0: {value: 'line-height: 0;'},
	line_height_1: {value: 'line-height: 1;'},
	line_height_xs: {value: 'line-height: var(--line_height_xs);'},
	line_height_sm: {value: 'line-height: var(--line_height_sm);'},
	line_height_md: {value: 'line-height: var(--line_height_md);'},
	line_height_lg: {value: 'line-height: var(--line_height_lg);'},
	line_height_xl: {value: 'line-height: var(--line_height_xl);'},
	size_xs: {value: 'font-size: var(--size_xs);'},
	size_sm: {value: 'font-size: var(--size_sm);'},
	size_md: {value: 'font-size: var(--size_md);'},
	size_lg: {value: 'font-size: var(--size_lg);'},
	size_xl: {value: 'font-size: var(--size_xl);'},
	size_xl2: {value: 'font-size: var(--size_xl2);'},
	size_xl3: {value: 'font-size: var(--size_xl3);'},
	size_xl4: {value: 'font-size: var(--size_xl4);'},
	size_xl5: {value: 'font-size: var(--size_xl5);'},
	size_xl6: {value: 'font-size: var(--size_xl6);'},
	size_xl7: {value: 'font-size: var(--size_xl7);'},
	size_xl8: {value: 'font-size: var(--size_xl8);'},
	size_xl9: {value: 'font-size: var(--size_xl9);'},
	icon_size_xs: {value: 'font-size: var(--icon_size_xs);'},
	icon_size_sm: {value: 'font-size: var(--icon_size_sm);'},
	icon_size_md: {value: 'font-size: var(--icon_size_md);'},
	icon_size_lg: {value: 'font-size: var(--icon_size_lg);'},
	icon_size_xl: {value: 'font-size: var(--icon_size_xl);'},
	icon_size_xl2: {value: 'font-size: var(--icon_size_xl2);'},
	icon_size_xl3: {value: 'font-size: var(--icon_size_xl3);'},
	text_align_start: {value: 'text-align: start;'},
	text_align_end: {value: 'text-align: end;'},
	text_align_left: {value: 'text-align: left;'},
	text_align_right: {value: 'text-align: right;'},
	text_align_center: {value: 'text-align: center;'},
	text_align_justify: {value: 'text-align: justify;'},
	text_align_justify_all: {value: 'text-align: justify-all;'},
	text_align_match_parent: {value: 'text-align: match-parent;'},
	vertical_align_baseline: {value: 'vertical-align: baseline;'},
	vertical_align_sub: {value: 'vertical-align: sub;'},
	vertical_align_super: {value: 'vertical-align: super;'},
	vertical_align_text_top: {value: 'vertical-align: text-top;'},
	vertical_align_text_bottom: {value: 'vertical-align: text-bottom;'},
	vertical_align_middle: {value: 'vertical-align: middle;'},
	vertical_align_top: {value: 'vertical-align: top;'},
	vertical_align_bottom: {value: 'vertical-align: bottom;'},
	white_space_normal: {value: 'white-space: normal;'},
	white_space_nowrap: {value: 'white-space: nowrap;'},
	white_space_pre: {value: 'white-space: pre;'},
	white_space_pre_wrap: {value: 'white-space: pre-wrap;'},
	white_space_pre_line: {value: 'white-space: pre-line;'},
	white_space_break_spaces: {value: 'white-space: break-spaces;'},

	/* TODO maybe use `initial` here instead of being consistent? because it looks weird */
	white_space_collapse_collapse: {value: 'white-space-collapse: collapse;'},
	white_space_collapse_preserve: {value: 'white-space-collapse: preserve;'},
	white_space_collapse_preserve_breaks: {value: 'white-space-collapse: preserve-breaks;'},
	white_space_collapse_preserve_spaces: {value: 'white-space-collapse: preserve-spaces;'},
	white_space_collapse_break_spaces: {value: 'white-space-collapse: break-spaces;'},

	/* TODO maybe use `initial` here instead of being consistent? because it looks weird */
	text_wrap_wrap: {value: 'text-wrap: wrap;'},
	text_wrap_nowrap: {value: 'text-wrap: nowrap;'},
	text_wrap_balance: {value: 'text-wrap: balance;'},
	text_wrap_pretty: {value: 'text-wrap: pretty;'},
	text_wrap_stable: {value: 'text-wrap: stable;'},
	ellipsis: {value: 'display: block;	white-space: nowrap;	overflow: hidden;	text-overflow: ellipsis;'},
	font_weight_100: {value: 'font-weight: 100;'},
	font_weight_200: {value: 'font-weight: 200;'},
	font_weight_300: {value: 'font-weight: 300;'},
	font_weight_400: {value: 'font-weight: 400;'},
	font_weight_500: {value: 'font-weight: 500;'},
	font_weight_600: {value: 'font-weight: 600;'},
	font_weight_700: {value: 'font-weight: 700;'},
	font_weight_800: {value: 'font-weight: 800;'},
	font_weight_900: {value: 'font-weight: 900;'},

	/*/

colors

*/
	text_color_0: {value: 'color: var(--text_color_0);'},
	text_color_1: {value: 'color: var(--text_color_1);'},
	text_color_2: {value: 'color: var(--text_color_2);'},
	text_color_3: {value: 'color: var(--text_color_3);'},
	text_color_4: {value: 'color: var(--text_color_4);'},
	text_color_5: {value: 'color: var(--text_color_5);'},
	text_color_6: {value: 'color: var(--text_color_6);'},
	text_color_7: {value: 'color: var(--text_color_7);'},
	text_color_8: {value: 'color: var(--text_color_8);'},
	text_color_9: {value: 'color: var(--text_color_9);'},
	text_color_10: {value: 'color: var(--text_color_10);'},
	darken_1: {value: 'background-color: var(--darken_1);'},
	darken_2: {value: 'background-color: var(--darken_2);'},
	darken_3: {value: 'background-color: var(--darken_3);'},
	darken_4: {value: 'background-color: var(--darken_4);'},
	darken_5: {value: 'background-color: var(--darken_5);'},
	darken_6: {value: 'background-color: var(--darken_6);'},
	darken_7: {value: 'background-color: var(--darken_7);'},
	darken_8: {value: 'background-color: var(--darken_8);'},
	darken_9: {value: 'background-color: var(--darken_9);'},
	lighten_1: {value: 'background-color: var(--lighten_1);'},
	lighten_2: {value: 'background-color: var(--lighten_2);'},
	lighten_3: {value: 'background-color: var(--lighten_3);'},
	lighten_4: {value: 'background-color: var(--lighten_4);'},
	lighten_5: {value: 'background-color: var(--lighten_5);'},
	lighten_6: {value: 'background-color: var(--lighten_6);'},
	lighten_7: {value: 'background-color: var(--lighten_7);'},
	lighten_8: {value: 'background-color: var(--lighten_8);'},
	lighten_9: {value: 'background-color: var(--lighten_9);'},
	bg: {value: 'background-color: var(--bg);'},
	fg: {value: 'background-color: var(--fg);'},
	bg_1: {value: 'background-color: var(--bg_1);'},
	bg_2: {value: 'background-color: var(--bg_2);'},
	bg_3: {value: 'background-color: var(--bg_3);'},
	bg_4: {value: 'background-color: var(--bg_4);'},
	bg_5: {value: 'background-color: var(--bg_5);'},
	bg_6: {value: 'background-color: var(--bg_6);'},
	bg_7: {value: 'background-color: var(--bg_7);'},
	bg_8: {value: 'background-color: var(--bg_8);'},
	bg_9: {value: 'background-color: var(--bg_9);'},
	fg_1: {value: 'background-color: var(--fg_1);'},
	fg_2: {value: 'background-color: var(--fg_2);'},
	fg_3: {value: 'background-color: var(--fg_3);'},
	fg_4: {value: 'background-color: var(--fg_4);'},
	fg_5: {value: 'background-color: var(--fg_5);'},
	fg_6: {value: 'background-color: var(--fg_6);'},
	fg_7: {value: 'background-color: var(--fg_7);'},
	fg_8: {value: 'background-color: var(--fg_8);'},
	fg_9: {value: 'background-color: var(--fg_9);'},
	color_darken_1: {value: 'color: var(--darken_1);'},
	color_darken_2: {value: 'color: var(--darken_2);'},
	color_darken_3: {value: 'color: var(--darken_3);'},
	color_darken_4: {value: 'color: var(--darken_4);'},
	color_darken_5: {value: 'color: var(--darken_5);'},
	color_darken_6: {value: 'color: var(--darken_6);'},
	color_darken_7: {value: 'color: var(--darken_7);'},
	color_darken_8: {value: 'color: var(--darken_8);'},
	color_darken_9: {value: 'color: var(--darken_9);'},
	color_lighten_1: {value: 'color: var(--lighten_1);'},
	color_lighten_2: {value: 'color: var(--lighten_2);'},
	color_lighten_3: {value: 'color: var(--lighten_3);'},
	color_lighten_4: {value: 'color: var(--lighten_4);'},
	color_lighten_5: {value: 'color: var(--lighten_5);'},
	color_lighten_6: {value: 'color: var(--lighten_6);'},
	color_lighten_7: {value: 'color: var(--lighten_7);'},
	color_lighten_8: {value: 'color: var(--lighten_8);'},
	color_lighten_9: {value: 'color: var(--lighten_9);'},
	color_bg: {value: 'color: var(--bg);'},
	color_fg: {value: 'color: var(--fg);'},
	color_bg_1: {value: 'color: var(--bg_1);'},
	color_bg_2: {value: 'color: var(--bg_2);'},
	color_bg_3: {value: 'color: var(--bg_3);'},
	color_bg_4: {value: 'color: var(--bg_4);'},
	color_bg_5: {value: 'color: var(--bg_5);'},
	color_bg_6: {value: 'color: var(--bg_6);'},
	color_bg_7: {value: 'color: var(--bg_7);'},
	color_bg_8: {value: 'color: var(--bg_8);'},
	color_bg_9: {value: 'color: var(--bg_9);'},
	color_fg_1: {value: 'color: var(--fg_1);'},
	color_fg_2: {value: 'color: var(--fg_2);'},
	color_fg_3: {value: 'color: var(--fg_3);'},
	color_fg_4: {value: 'color: var(--fg_4);'},
	color_fg_5: {value: 'color: var(--fg_5);'},
	color_fg_6: {value: 'color: var(--fg_6);'},
	color_fg_7: {value: 'color: var(--fg_7);'},
	color_fg_8: {value: 'color: var(--fg_8);'},
	color_fg_9: {value: 'color: var(--fg_9);'},
	hue_a: {value: '--hue: var(--hue_a);'},
	hue_b: {value: '--hue: var(--hue_b);'},
	hue_c: {value: '--hue: var(--hue_c);'},
	hue_d: {value: '--hue: var(--hue_d);'},
	hue_e: {value: '--hue: var(--hue_e);'},
	hue_f: {value: '--hue: var(--hue_f);'},
	hue_g: {value: '--hue: var(--hue_g);'},
	hue_h: {value: '--hue: var(--hue_h);'},
	hue_i: {value: '--hue: var(--hue_i);'},
	color_a_1: {value: 'color: var(--color_a_1);'},
	color_a_2: {value: 'color: var(--color_a_2);'},
	color_a_3: {value: 'color: var(--color_a_3);'},
	color_a_4: {value: 'color: var(--color_a_4);'},
	color_a_5: {value: 'color: var(--color_a_5);'},
	color_a_6: {value: 'color: var(--color_a_6);'},
	color_a_7: {value: 'color: var(--color_a_7);'},
	color_a_8: {value: 'color: var(--color_a_8);'},
	color_a_9: {value: 'color: var(--color_a_9);'},
	color_b_1: {value: 'color: var(--color_b_1);'},
	color_b_2: {value: 'color: var(--color_b_2);'},
	color_b_3: {value: 'color: var(--color_b_3);'},
	color_b_4: {value: 'color: var(--color_b_4);'},
	color_b_5: {value: 'color: var(--color_b_5);'},
	color_b_6: {value: 'color: var(--color_b_6);'},
	color_b_7: {value: 'color: var(--color_b_7);'},
	color_b_8: {value: 'color: var(--color_b_8);'},
	color_b_9: {value: 'color: var(--color_b_9);'},
	color_c_1: {value: 'color: var(--color_c_1);'},
	color_c_2: {value: 'color: var(--color_c_2);'},
	color_c_3: {value: 'color: var(--color_c_3);'},
	color_c_4: {value: 'color: var(--color_c_4);'},
	color_c_5: {value: 'color: var(--color_c_5);'},
	color_c_6: {value: 'color: var(--color_c_6);'},
	color_c_7: {value: 'color: var(--color_c_7);'},
	color_c_8: {value: 'color: var(--color_c_8);'},
	color_c_9: {value: 'color: var(--color_c_9);'},
	color_d_1: {value: 'color: var(--color_d_1);'},
	color_d_2: {value: 'color: var(--color_d_2);'},
	color_d_3: {value: 'color: var(--color_d_3);'},
	color_d_4: {value: 'color: var(--color_d_4);'},
	color_d_5: {value: 'color: var(--color_d_5);'},
	color_d_6: {value: 'color: var(--color_d_6);'},
	color_d_7: {value: 'color: var(--color_d_7);'},
	color_d_8: {value: 'color: var(--color_d_8);'},
	color_d_9: {value: 'color: var(--color_d_9);'},
	color_e_1: {value: 'color: var(--color_e_1);'},
	color_e_2: {value: 'color: var(--color_e_2);'},
	color_e_3: {value: 'color: var(--color_e_3);'},
	color_e_4: {value: 'color: var(--color_e_4);'},
	color_e_5: {value: 'color: var(--color_e_5);'},
	color_e_6: {value: 'color: var(--color_e_6);'},
	color_e_7: {value: 'color: var(--color_e_7);'},
	color_e_8: {value: 'color: var(--color_e_8);'},
	color_e_9: {value: 'color: var(--color_e_9);'},
	color_f_1: {value: 'color: var(--color_f_1);'},
	color_f_2: {value: 'color: var(--color_f_2);'},
	color_f_3: {value: 'color: var(--color_f_3);'},
	color_f_4: {value: 'color: var(--color_f_4);'},
	color_f_5: {value: 'color: var(--color_f_5);'},
	color_f_6: {value: 'color: var(--color_f_6);'},
	color_f_7: {value: 'color: var(--color_f_7);'},
	color_f_8: {value: 'color: var(--color_f_8);'},
	color_f_9: {value: 'color: var(--color_f_9);'},
	color_g_1: {value: 'color: var(--color_g_1);'},
	color_g_2: {value: 'color: var(--color_g_2);'},
	color_g_3: {value: 'color: var(--color_g_3);'},
	color_g_4: {value: 'color: var(--color_g_4);'},
	color_g_5: {value: 'color: var(--color_g_5);'},
	color_g_6: {value: 'color: var(--color_g_6);'},
	color_g_7: {value: 'color: var(--color_g_7);'},
	color_g_8: {value: 'color: var(--color_g_8);'},
	color_g_9: {value: 'color: var(--color_g_9);'},
	color_h_1: {value: 'color: var(--color_h_1);'},
	color_h_2: {value: 'color: var(--color_h_2);'},
	color_h_3: {value: 'color: var(--color_h_3);'},
	color_h_4: {value: 'color: var(--color_h_4);'},
	color_h_5: {value: 'color: var(--color_h_5);'},
	color_h_6: {value: 'color: var(--color_h_6);'},
	color_h_7: {value: 'color: var(--color_h_7);'},
	color_h_8: {value: 'color: var(--color_h_8);'},
	color_h_9: {value: 'color: var(--color_h_9);'},
	color_i_1: {value: 'color: var(--color_i_1);'},
	color_i_2: {value: 'color: var(--color_i_2);'},
	color_i_3: {value: 'color: var(--color_i_3);'},
	color_i_4: {value: 'color: var(--color_i_4);'},
	color_i_5: {value: 'color: var(--color_i_5);'},
	color_i_6: {value: 'color: var(--color_i_6);'},
	color_i_7: {value: 'color: var(--color_i_7);'},
	color_i_8: {value: 'color: var(--color_i_8);'},
	color_i_9: {value: 'color: var(--color_i_9);'},
	bg_a_1: {value: 'background-color: var(--color_a_1);'},
	bg_a_2: {value: 'background-color: var(--color_a_2);'},
	bg_a_3: {value: 'background-color: var(--color_a_3);'},
	bg_a_4: {value: 'background-color: var(--color_a_4);'},
	bg_a_5: {value: 'background-color: var(--color_a_5);'},
	bg_a_6: {value: 'background-color: var(--color_a_6);'},
	bg_a_7: {value: 'background-color: var(--color_a_7);'},
	bg_a_8: {value: 'background-color: var(--color_a_8);'},
	bg_a_9: {value: 'background-color: var(--color_a_9);'},
	bg_b_1: {value: 'background-color: var(--color_b_1);'},
	bg_b_2: {value: 'background-color: var(--color_b_2);'},
	bg_b_3: {value: 'background-color: var(--color_b_3);'},
	bg_b_4: {value: 'background-color: var(--color_b_4);'},
	bg_b_5: {value: 'background-color: var(--color_b_5);'},
	bg_b_6: {value: 'background-color: var(--color_b_6);'},
	bg_b_7: {value: 'background-color: var(--color_b_7);'},
	bg_b_8: {value: 'background-color: var(--color_b_8);'},
	bg_b_9: {value: 'background-color: var(--color_b_9);'},
	bg_c_1: {value: 'background-color: var(--color_c_1);'},
	bg_c_2: {value: 'background-color: var(--color_c_2);'},
	bg_c_3: {value: 'background-color: var(--color_c_3);'},
	bg_c_4: {value: 'background-color: var(--color_c_4);'},
	bg_c_5: {value: 'background-color: var(--color_c_5);'},
	bg_c_6: {value: 'background-color: var(--color_c_6);'},
	bg_c_7: {value: 'background-color: var(--color_c_7);'},
	bg_c_8: {value: 'background-color: var(--color_c_8);'},
	bg_c_9: {value: 'background-color: var(--color_c_9);'},
	bg_d_1: {value: 'background-color: var(--color_d_1);'},
	bg_d_2: {value: 'background-color: var(--color_d_2);'},
	bg_d_3: {value: 'background-color: var(--color_d_3);'},
	bg_d_4: {value: 'background-color: var(--color_d_4);'},
	bg_d_5: {value: 'background-color: var(--color_d_5);'},
	bg_d_6: {value: 'background-color: var(--color_d_6);'},
	bg_d_7: {value: 'background-color: var(--color_d_7);'},
	bg_d_8: {value: 'background-color: var(--color_d_8);'},
	bg_d_9: {value: 'background-color: var(--color_d_9);'},
	bg_e_1: {value: 'background-color: var(--color_e_1);'},
	bg_e_2: {value: 'background-color: var(--color_e_2);'},
	bg_e_3: {value: 'background-color: var(--color_e_3);'},
	bg_e_4: {value: 'background-color: var(--color_e_4);'},
	bg_e_5: {value: 'background-color: var(--color_e_5);'},
	bg_e_6: {value: 'background-color: var(--color_e_6);'},
	bg_e_7: {value: 'background-color: var(--color_e_7);'},
	bg_e_8: {value: 'background-color: var(--color_e_8);'},
	bg_e_9: {value: 'background-color: var(--color_e_9);'},
	bg_f_1: {value: 'background-color: var(--color_f_1);'},
	bg_f_2: {value: 'background-color: var(--color_f_2);'},
	bg_f_3: {value: 'background-color: var(--color_f_3);'},
	bg_f_4: {value: 'background-color: var(--color_f_4);'},
	bg_f_5: {value: 'background-color: var(--color_f_5);'},
	bg_f_6: {value: 'background-color: var(--color_f_6);'},
	bg_f_7: {value: 'background-color: var(--color_f_7);'},
	bg_f_8: {value: 'background-color: var(--color_f_8);'},
	bg_f_9: {value: 'background-color: var(--color_f_9);'},
	bg_g_1: {value: 'background-color: var(--color_g_1);'},
	bg_g_2: {value: 'background-color: var(--color_g_2);'},
	bg_g_3: {value: 'background-color: var(--color_g_3);'},
	bg_g_4: {value: 'background-color: var(--color_g_4);'},
	bg_g_5: {value: 'background-color: var(--color_g_5);'},
	bg_g_6: {value: 'background-color: var(--color_g_6);'},
	bg_g_7: {value: 'background-color: var(--color_g_7);'},
	bg_g_8: {value: 'background-color: var(--color_g_8);'},
	bg_g_9: {value: 'background-color: var(--color_g_9);'},
	bg_h_1: {value: 'background-color: var(--color_h_1);'},
	bg_h_2: {value: 'background-color: var(--color_h_2);'},
	bg_h_3: {value: 'background-color: var(--color_h_3);'},
	bg_h_4: {value: 'background-color: var(--color_h_4);'},
	bg_h_5: {value: 'background-color: var(--color_h_5);'},
	bg_h_6: {value: 'background-color: var(--color_h_6);'},
	bg_h_7: {value: 'background-color: var(--color_h_7);'},
	bg_h_8: {value: 'background-color: var(--color_h_8);'},
	bg_h_9: {value: 'background-color: var(--color_h_9);'},
	bg_i_1: {value: 'background-color: var(--color_i_1);'},
	bg_i_2: {value: 'background-color: var(--color_i_2);'},
	bg_i_3: {value: 'background-color: var(--color_i_3);'},
	bg_i_4: {value: 'background-color: var(--color_i_4);'},
	bg_i_5: {value: 'background-color: var(--color_i_5);'},
	bg_i_6: {value: 'background-color: var(--color_i_6);'},
	bg_i_7: {value: 'background-color: var(--color_i_7);'},
	bg_i_8: {value: 'background-color: var(--color_i_8);'},
	bg_i_9: {value: 'background-color: var(--color_i_9);'},
	border_color_1: {value: 'border-color: var(--border_color_1);'},
	border_color_2: {value: 'border-color: var(--border_color_2);'},
	border_color_3: {value: 'border-color: var(--border_color_3);'},
	border_color_4: {value: 'border-color: var(--border_color_4);'},
	border_color_5: {value: 'border-color: var(--border_color_5);'},
	border_color_a: {value: 'border-color: var(--border_color_a);'},
	border_color_b: {value: 'border-color: var(--border_color_b);'},
	border_color_c: {value: 'border-color: var(--border_color_c);'},
	border_color_d: {value: 'border-color: var(--border_color_d);'},
	border_color_e: {value: 'border-color: var(--border_color_e);'},
	border_color_f: {value: 'border-color: var(--border_color_f);'},
	border_color_g: {value: 'border-color: var(--border_color_g);'},
	border_color_h: {value: 'border-color: var(--border_color_h);'},
	border_color_i: {value: 'border-color: var(--border_color_i);'},
	border_color_transparent: {value: 'border-color: transparent;'},
	border_width_0: {value: 'border-width: 0;'},
	border_width_1: {value: 'border-width: var(--border_width_1);'},
	border_width_2: {value: 'border-width: var(--border_width_2);'},
	border_width_3: {value: 'border-width: var(--border_width_3);'},
	border_width_4: {value: 'border-width: var(--border_width_4);'},
	border_width_5: {value: 'border-width: var(--border_width_5);'},
	border_width_6: {value: 'border-width: var(--border_width_6);'},
	outline_width_0: {value: 'outline-width: 0;'},
	outline_width_1: {value: 'outline-width: var(--outline_width_1);'},
	outline_width_2: {value: 'outline-width: var(--outline_width_2);'},
	outline_width_3: {value: 'outline-width: var(--outline_width_3);'},

	/* TODO add the top/right/bottom/left variants */
	/* @see https://developer.mozilla.org/en-US/docs/Web/CSS/border-style */
	border_none: {value: 'border-style: none;'},
	border_hidden: {value: 'border-style: hidden;'},
	border_dotted: {value: 'border-style: dotted;'},
	border_dashed: {value: 'border-style: dashed;'},
	border_solid: {value: 'border-style: solid;'},
	border_double: {value: 'border-style: double;'},
	border_groove: {value: 'border-style: groove;'},
	border_ridge: {value: 'border-style: ridge;'},
	border_inset: {value: 'border-style: inset;'},
	border_outset: {value: 'border-style: outset;'},
	radius_100: {value: 'border-radius: 100%;'},
	radius_50: {value: 'border-radius: 50%;'},
	radius_0: {value: 'border-radius: 0;'},
	radius_xs3: {value: 'border-radius: var(--radius_xs3);'},
	radius_xs2: {value: 'border-radius: var(--radius_xs2);'},
	radius_xs: {value: 'border-radius: var(--radius_xs);'},
	radius_sm: {value: 'border-radius: var(--radius_sm);'},
	radius_md: {value: 'border-radius: var(--radius_md);'},
	radius_lg: {value: 'border-radius: var(--radius_lg);'},
	radius_xl: {value: 'border-radius: var(--radius_xl);'},

	/*

shading

*/
	fade_0: {value: 'opacity: 0;'},
	fade_100: {value: 'opacity: 1;'},
	fade_1: {value: 'opacity: var(--fade_1);'},
	fade_2: {value: 'opacity: var(--fade_2);'},
	fade_3: {value: 'opacity: var(--fade_3);'},
	fade_4: {value: 'opacity: var(--fade_4);'},
	fade_5: {value: 'opacity: var(--fade_5);'},
	fade_6: {value: 'opacity: var(--fade_6);'},

	/*/

shadows

*/
	shadow_xs: {
		value:
			'--shadow_alpha: var(--shadow_alpha_1) box-shadow: var(--shadow_xs) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_1)), transparent);',
	},
	shadow_sm: {
		value:
			'box-shadow: var(--shadow_sm) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_2)), transparent);',
	},
	shadow_md: {
		value:
			'box-shadow: var(--shadow_md) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_3)), transparent);',
	},
	shadow_lg: {
		value:
			'box-shadow: var(--shadow_lg) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_4)), transparent);',
	},
	shadow_xl: {
		value:
			'box-shadow: var(--shadow_xl) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_5)), transparent);',
	},
	shadow_top_xs: {
		value:
			'box-shadow: var(--shadow_top_xs) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_1)), transparent);',
	},
	shadow_top_sm: {
		value:
			'box-shadow: var(--shadow_top_sm) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_2)), transparent);',
	},
	shadow_top_md: {
		value:
			'box-shadow: var(--shadow_top_md) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_3)), transparent);',
	},
	shadow_top_lg: {
		value:
			'box-shadow: var(--shadow_top_lg) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_4)), transparent);',
	},
	shadow_top_xl: {
		value:
			'box-shadow: var(--shadow_top_xl) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_5)), transparent);',
	},
	shadow_bottom_xs: {
		value:
			'box-shadow: var(--shadow_bottom_xs) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_1)), transparent);',
	},
	shadow_bottom_sm: {
		value:
			'box-shadow: var(--shadow_bottom_sm) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_2)), transparent);',
	},
	shadow_bottom_md: {
		value:
			'box-shadow: var(--shadow_bottom_md) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_3)), transparent);',
	},
	shadow_bottom_lg: {
		value:
			'box-shadow: var(--shadow_bottom_lg) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_4)), transparent);',
	},
	shadow_bottom_xl: {
		value:
			'box-shadow: var(--shadow_bottom_xl) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_5)), transparent);',
	},
	shadow_inset_xs: {
		value:
			'box-shadow: var(--shadow_inset_xs) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_1)), transparent);',
	},
	shadow_inset_sm: {
		value:
			'box-shadow: var(--shadow_inset_sm) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_2)), transparent);',
	},
	shadow_inset_md: {
		value:
			'box-shadow: var(--shadow_inset_md) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_3)), transparent);',
	},
	shadow_inset_lg: {
		value:
			'box-shadow: var(--shadow_inset_lg) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_4)), transparent);',
	},
	shadow_inset_xl: {
		value:
			'box-shadow: var(--shadow_inset_xl) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_5)), transparent);',
	},
	shadow_inset_top_xs: {
		value:
			'box-shadow: var(--shadow_inset_top_xs) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_1)), transparent);',
	},
	shadow_inset_top_sm: {
		value:
			'box-shadow: var(--shadow_inset_top_sm) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_2)), transparent);',
	},
	shadow_inset_top_md: {
		value:
			'box-shadow: var(--shadow_inset_top_md) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_3)), transparent);',
	},
	shadow_inset_top_lg: {
		value:
			'box-shadow: var(--shadow_inset_top_lg) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_4)), transparent);',
	},
	shadow_inset_top_xl: {
		value:
			'box-shadow: var(--shadow_inset_top_xl) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_5)), transparent);',
	},
	shadow_inset_bottom_xs: {
		value:
			'box-shadow: var(--shadow_inset_bottom_xs) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_1)), transparent);',
	},
	shadow_inset_bottom_sm: {
		value:
			'box-shadow: var(--shadow_inset_bottom_sm) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_2)), transparent);',
	},
	shadow_inset_bottom_md: {
		value:
			'box-shadow: var(--shadow_inset_bottom_md) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_3)), transparent);',
	},
	shadow_inset_bottom_lg: {
		value:
			'box-shadow: var(--shadow_inset_bottom_lg) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_4)), transparent);',
	},
	shadow_inset_bottom_xl: {
		value:
			'box-shadow: var(--shadow_inset_bottom_xl) color-mix(in hsl, var(--shadow_color) var(--shadow_alpha, var(--shadow_alpha_5)), transparent);',
	},
	shadow_color_highlight: {value: '--shadow_color: var(--shadow_color_highlight);'},
	shadow_color_glow: {value: '--shadow_color: var(--shadow_color_glow);'},
	shadow_color_shroud: {value: '--shadow_color: var(--shadow_color_shroud);'},
	shadow_color_a: {value: '--shadow_color: var(--shadow_color_a);'},
	shadow_color_b: {value: '--shadow_color: var(--shadow_color_b);'},
	shadow_color_c: {value: '--shadow_color: var(--shadow_color_c);'},
	shadow_color_d: {value: '--shadow_color: var(--shadow_color_d);'},
	shadow_color_e: {value: '--shadow_color: var(--shadow_color_e);'},
	shadow_color_f: {value: '--shadow_color: var(--shadow_color_f);'},
	shadow_color_g: {value: '--shadow_color: var(--shadow_color_g);'},
	shadow_color_h: {value: '--shadow_color: var(--shadow_color_h);'},
	shadow_color_i: {value: '--shadow_color: var(--shadow_color_i);'},
	shadow_alpha_1: {value: '--shadow_alpha: var(--shadow_alpha_1);'},
	shadow_alpha_2: {value: '--shadow_alpha: var(--shadow_alpha_2);'},
	shadow_alpha_3: {value: '--shadow_alpha: var(--shadow_alpha_3);'},
	shadow_alpha_4: {value: '--shadow_alpha: var(--shadow_alpha_4);'},
	shadow_alpha_5: {value: '--shadow_alpha: var(--shadow_alpha_5);'},

	/* higher specificity */
	/* TODO which order should these be in? */
	shadow_inherit: {value: 'box-shadow: inherit;'},
	shadow_none: {value: 'box-shadow: none;'},

	/*/

layout

*/
	w_0: {value: 'width: 0;'},
	w_100: {value: 'width: 100%;'},
	w_auto: {value: 'width: auto;'},
	w_max_content: {value: 'width: max-content;'},
	w_min_content: {value: 'width: min-content;'},
	w_fit_content: {value: 'width: fit-content;'},
	w_stretch: {value: 'width: stretch;'},
	w_xs: {value: 'width: var(--space_xs);'},
	w_sm: {value: 'width: var(--space_sm);'},
	w_md: {value: 'width: var(--space_md);'},
	w_lg: {value: 'width: var(--space_lg);'},
	w_xl: {value: 'width: var(--space_xl);'},
	w_xl2: {value: 'width: var(--space_xl2);'},
	w_xl3: {value: 'width: var(--space_xl3);'},
	w_xl4: {value: 'width: var(--space_xl4);'},
	w_xl5: {value: 'width: var(--space_xl5);'},
	w_xl6: {value: 'width: var(--space_xl6);'},
	w_xl7: {value: 'width: var(--space_xl7);'},
	w_xl8: {value: 'width: var(--space_xl8);'},
	w_xl9: {value: 'width: var(--space_xl9);'},
	w_xl10: {value: 'width: var(--space_xl10);'},
	w_xl11: {value: 'width: var(--space_xl11);'},
	w_xl12: {value: 'width: var(--space_xl12);'},
	w_xl13: {value: 'width: var(--space_xl13);'},
	w_xl14: {value: 'width: var(--space_xl14);'},
	w_xl15: {value: 'width: var(--space_xl15);'},
	h_0: {value: 'height: 0;'},
	h_100: {value: 'height: 100%;'},
	h_auto: {value: 'height: auto;'},
	h_max_content: {value: 'height: max-content;'},
	h_min_content: {value: 'height: min-content;'},
	h_fit_content: {value: 'height: fit-content;'},
	h_stretch: {value: 'height: stretch;'},
	h_xs: {value: 'height: var(--space_xs);'},
	h_sm: {value: 'height: var(--space_sm);'},
	h_md: {value: 'height: var(--space_md);'},
	h_lg: {value: 'height: var(--space_lg);'},
	h_xl: {value: 'height: var(--space_xl);'},
	h_xl2: {value: 'height: var(--space_xl2);'},
	h_xl3: {value: 'height: var(--space_xl3);'},
	h_xl4: {value: 'height: var(--space_xl4);'},
	h_xl5: {value: 'height: var(--space_xl5);'},
	h_xl6: {value: 'height: var(--space_xl6);'},
	h_xl7: {value: 'height: var(--space_xl7);'},
	h_xl8: {value: 'height: var(--space_xl8);'},
	h_xl9: {value: 'height: var(--space_xl9);'},
	h_xl10: {value: 'height: var(--space_xl10);'},
	h_xl11: {value: 'height: var(--space_xl11);'},
	h_xl12: {value: 'height: var(--space_xl12);'},
	h_xl13: {value: 'height: var(--space_xl13);'},
	h_xl14: {value: 'height: var(--space_xl14);'},
	h_xl15: {value: 'height: var(--space_xl15);'},

	/* TODO % variants? */
	t_0: {value: 'top: 0;'},
	t_100: {value: 'top: 100%;'},
	t_auto: {value: 'top: auto;'},
	t_xs: {value: 'top: var(--space_xs);'},
	t_sm: {value: 'top: var(--space_sm);'},
	t_md: {value: 'top: var(--space_md);'},
	t_lg: {value: 'top: var(--space_lg);'},
	t_xl: {value: 'top: var(--space_xl);'},
	t_xl2: {value: 'top: var(--space_xl2);'},
	t_xl3: {value: 'top: var(--space_xl3);'},
	t_xl4: {value: 'top: var(--space_xl4);'},
	t_xl5: {value: 'top: var(--space_xl5);'},
	t_xl6: {value: 'top: var(--space_xl6);'},
	t_xl7: {value: 'top: var(--space_xl7);'},
	t_xl8: {value: 'top: var(--space_xl8);'},
	t_xl9: {value: 'top: var(--space_xl9);'},
	t_xl10: {value: 'top: var(--space_xl10);'},
	t_xl11: {value: 'top: var(--space_xl11);'},
	t_xl12: {value: 'top: var(--space_xl12);'},
	t_xl13: {value: 'top: var(--space_xl13);'},
	t_xl14: {value: 'top: var(--space_xl14);'},
	t_xl15: {value: 'top: var(--space_xl15);'},
	b_0: {value: 'bottom: 0;'},
	b_100: {value: 'bottom: 100%;'},
	b_auto: {value: 'bottom: auto;'},
	b_xs: {value: 'bottom: var(--space_xs);'},
	b_sm: {value: 'bottom: var(--space_sm);'},
	b_md: {value: 'bottom: var(--space_md);'},
	b_lg: {value: 'bottom: var(--space_lg);'},
	b_xl: {value: 'bottom: var(--space_xl);'},
	b_xl2: {value: 'bottom: var(--space_xl2);'},
	b_xl3: {value: 'bottom: var(--space_xl3);'},
	b_xl4: {value: 'bottom: var(--space_xl4);'},
	b_xl5: {value: 'bottom: var(--space_xl5);'},
	b_xl6: {value: 'bottom: var(--space_xl6);'},
	b_xl7: {value: 'bottom: var(--space_xl7);'},
	b_xl8: {value: 'bottom: var(--space_xl8);'},
	b_xl9: {value: 'bottom: var(--space_xl9);'},
	b_xl10: {value: 'bottom: var(--space_xl10);'},
	b_xl11: {value: 'bottom: var(--space_xl11);'},
	b_xl12: {value: 'bottom: var(--space_xl12);'},
	b_xl13: {value: 'bottom: var(--space_xl13);'},
	b_xl14: {value: 'bottom: var(--space_xl14);'},
	b_xl15: {value: 'bottom: var(--space_xl15);'},
	l_0: {value: 'left: 0;'},
	l_100: {value: 'left: 100%;'},
	l_auto: {value: 'left: auto;'},
	l_xs: {value: 'left: var(--space_xs);'},
	l_sm: {value: 'left: var(--space_sm);'},
	l_md: {value: 'left: var(--space_md);'},
	l_lg: {value: 'left: var(--space_lg);'},
	l_xl: {value: 'left: var(--space_xl);'},
	l_xl2: {value: 'left: var(--space_xl2);'},
	l_xl3: {value: 'left: var(--space_xl3);'},
	l_xl4: {value: 'left: var(--space_xl4);'},
	l_xl5: {value: 'left: var(--space_xl5);'},
	l_xl6: {value: 'left: var(--space_xl6);'},
	l_xl7: {value: 'left: var(--space_xl7);'},
	l_xl8: {value: 'left: var(--space_xl8);'},
	l_xl9: {value: 'left: var(--space_xl9);'},
	l_xl10: {value: 'left: var(--space_xl10);'},
	l_xl11: {value: 'left: var(--space_xl11);'},
	l_xl12: {value: 'left: var(--space_xl12);'},
	l_xl13: {value: 'left: var(--space_xl13);'},
	l_xl14: {value: 'left: var(--space_xl14);'},
	l_xl15: {value: 'left: var(--space_xl15);'},
	r_0: {value: 'right: 0;'},
	r_100: {value: 'right: 100%;'},
	r_auto: {value: 'right: auto;'},
	r_xs: {value: 'right: var(--space_xs);'},
	r_sm: {value: 'right: var(--space_sm);'},
	r_md: {value: 'right: var(--space_md);'},
	r_lg: {value: 'right: var(--space_lg);'},
	r_xl: {value: 'right: var(--space_xl);'},
	r_xl2: {value: 'right: var(--space_xl2);'},
	r_xl3: {value: 'right: var(--space_xl3);'},
	r_xl4: {value: 'right: var(--space_xl4);'},
	r_xl5: {value: 'right: var(--space_xl5);'},
	r_xl6: {value: 'right: var(--space_xl6);'},
	r_xl7: {value: 'right: var(--space_xl7);'},
	r_xl8: {value: 'right: var(--space_xl8);'},
	r_xl9: {value: 'right: var(--space_xl9);'},
	r_xl10: {value: 'right: var(--space_xl10);'},
	r_xl11: {value: 'right: var(--space_xl11);'},
	r_xl12: {value: 'right: var(--space_xl12);'},
	r_xl13: {value: 'right: var(--space_xl13);'},
	r_xl14: {value: 'right: var(--space_xl14);'},
	r_xl15: {value: 'right: var(--space_xl15);'},
	p_0: {value: 'padding: 0;'},
	p_xs5: {value: 'padding: var(--space_xs5);'},
	p_xs4: {value: 'padding: var(--space_xs4);'},
	p_xs3: {value: 'padding: var(--space_xs3);'},
	p_xs2: {value: 'padding: var(--space_xs2);'},
	p_xs: {value: 'padding: var(--space_xs);'},
	p_sm: {value: 'padding: var(--space_sm);'},
	p_md: {value: 'padding: var(--space_md);'},
	p_lg: {value: 'padding: var(--space_lg);'},
	p_xl: {value: 'padding: var(--space_xl);'},
	p_xl2: {value: 'padding: var(--space_xl2);'},
	p_xl3: {value: 'padding: var(--space_xl3);'},
	p_xl4: {value: 'padding: var(--space_xl4);'},
	p_xl5: {value: 'padding: var(--space_xl5);'},
	p_xl6: {value: 'padding: var(--space_xl6);'},
	p_xl7: {value: 'padding: var(--space_xl7);'},
	p_xl8: {value: 'padding: var(--space_xl8);'},
	p_xl9: {value: 'padding: var(--space_xl9);'},
	p_xl10: {value: 'padding: var(--space_xl10);'},
	p_xl11: {value: 'padding: var(--space_xl11);'},
	p_xl12: {value: 'padding: var(--space_xl12);'},
	p_xl13: {value: 'padding: var(--space_xl13);'},
	p_xl14: {value: 'padding: var(--space_xl14);'},
	p_xl15: {value: 'padding: var(--space_xl15);'},
	pt_0: {value: 'padding-top: 0;'},
	pt_xs5: {value: 'padding-top: var(--space_xs5);'},
	pt_xs4: {value: 'padding-top: var(--space_xs4);'},
	pt_xs3: {value: 'padding-top: var(--space_xs3);'},
	pt_xs2: {value: 'padding-top: var(--space_xs2);'},
	pt_xs: {value: 'padding-top: var(--space_xs);'},
	pt_sm: {value: 'padding-top: var(--space_sm);'},
	pt_md: {value: 'padding-top: var(--space_md);'},
	pt_lg: {value: 'padding-top: var(--space_lg);'},
	pt_xl: {value: 'padding-top: var(--space_xl);'},
	pt_xl2: {value: 'padding-top: var(--space_xl2);'},
	pt_xl3: {value: 'padding-top: var(--space_xl3);'},
	pt_xl4: {value: 'padding-top: var(--space_xl4);'},
	pt_xl5: {value: 'padding-top: var(--space_xl5);'},
	pt_xl6: {value: 'padding-top: var(--space_xl6);'},
	pt_xl7: {value: 'padding-top: var(--space_xl7);'},
	pt_xl8: {value: 'padding-top: var(--space_xl8);'},
	pt_xl9: {value: 'padding-top: var(--space_xl9);'},
	pt_xl10: {value: 'padding-top: var(--space_xl10);'},
	pt_xl11: {value: 'padding-top: var(--space_xl11);'},
	pt_xl12: {value: 'padding-top: var(--space_xl12);'},
	pt_xl13: {value: 'padding-top: var(--space_xl13);'},
	pt_xl14: {value: 'padding-top: var(--space_xl14);'},
	pt_xl15: {value: 'padding-top: var(--space_xl15);'},
	pr_0: {value: 'padding-right: 0;'},
	pr_xs5: {value: 'padding-right: var(--space_xs5);'},
	pr_xs4: {value: 'padding-right: var(--space_xs4);'},
	pr_xs3: {value: 'padding-right: var(--space_xs3);'},
	pr_xs2: {value: 'padding-right: var(--space_xs2);'},
	pr_xs: {value: 'padding-right: var(--space_xs);'},
	pr_sm: {value: 'padding-right: var(--space_sm);'},
	pr_md: {value: 'padding-right: var(--space_md);'},
	pr_lg: {value: 'padding-right: var(--space_lg);'},
	pr_xl: {value: 'padding-right: var(--space_xl);'},
	pr_xl2: {value: 'padding-right: var(--space_xl2);'},
	pr_xl3: {value: 'padding-right: var(--space_xl3);'},
	pr_xl4: {value: 'padding-right: var(--space_xl4);'},
	pr_xl5: {value: 'padding-right: var(--space_xl5);'},
	pr_xl6: {value: 'padding-right: var(--space_xl6);'},
	pr_xl7: {value: 'padding-right: var(--space_xl7);'},
	pr_xl8: {value: 'padding-right: var(--space_xl8);'},
	pr_xl9: {value: 'padding-right: var(--space_xl9);'},
	pr_xl10: {value: 'padding-right: var(--space_xl10);'},
	pr_xl11: {value: 'padding-right: var(--space_xl11);'},
	pr_xl12: {value: 'padding-right: var(--space_xl12);'},
	pr_xl13: {value: 'padding-right: var(--space_xl13);'},
	pr_xl14: {value: 'padding-right: var(--space_xl14);'},
	pr_xl15: {value: 'padding-right: var(--space_xl15);'},
	pb_0: {value: 'padding-bottom: 0;'},
	pb_xs5: {value: 'padding-bottom: var(--space_xs5);'},
	pb_xs4: {value: 'padding-bottom: var(--space_xs4);'},
	pb_xs3: {value: 'padding-bottom: var(--space_xs3);'},
	pb_xs2: {value: 'padding-bottom: var(--space_xs2);'},
	pb_xs: {value: 'padding-bottom: var(--space_xs);'},
	pb_sm: {value: 'padding-bottom: var(--space_sm);'},
	pb_md: {value: 'padding-bottom: var(--space_md);'},
	pb_lg: {value: 'padding-bottom: var(--space_lg);'},
	pb_xl: {value: 'padding-bottom: var(--space_xl);'},
	pb_xl2: {value: 'padding-bottom: var(--space_xl2);'},
	pb_xl3: {value: 'padding-bottom: var(--space_xl3);'},
	pb_xl4: {value: 'padding-bottom: var(--space_xl4);'},
	pb_xl5: {value: 'padding-bottom: var(--space_xl5);'},
	pb_xl6: {value: 'padding-bottom: var(--space_xl6);'},
	pb_xl7: {value: 'padding-bottom: var(--space_xl7);'},
	pb_xl8: {value: 'padding-bottom: var(--space_xl8);'},
	pb_xl9: {value: 'padding-bottom: var(--space_xl9);'},
	pb_xl10: {value: 'padding-bottom: var(--space_xl10);'},
	pb_xl11: {value: 'padding-bottom: var(--space_xl11);'},
	pb_xl12: {value: 'padding-bottom: var(--space_xl12);'},
	pb_xl13: {value: 'padding-bottom: var(--space_xl13);'},
	pb_xl14: {value: 'padding-bottom: var(--space_xl14);'},
	pb_xl15: {value: 'padding-bottom: var(--space_xl15);'},
	pl_0: {value: 'padding-left: 0;'},
	pl_xs5: {value: 'padding-left: var(--space_xs5);'},
	pl_xs4: {value: 'padding-left: var(--space_xs4);'},
	pl_xs3: {value: 'padding-left: var(--space_xs3);'},
	pl_xs2: {value: 'padding-left: var(--space_xs2);'},
	pl_xs: {value: 'padding-left: var(--space_xs);'},
	pl_sm: {value: 'padding-left: var(--space_sm);'},
	pl_md: {value: 'padding-left: var(--space_md);'},
	pl_lg: {value: 'padding-left: var(--space_lg);'},
	pl_xl: {value: 'padding-left: var(--space_xl);'},
	pl_xl2: {value: 'padding-left: var(--space_xl2);'},
	pl_xl3: {value: 'padding-left: var(--space_xl3);'},
	pl_xl4: {value: 'padding-left: var(--space_xl4);'},
	pl_xl5: {value: 'padding-left: var(--space_xl5);'},
	pl_xl6: {value: 'padding-left: var(--space_xl6);'},
	pl_xl7: {value: 'padding-left: var(--space_xl7);'},
	pl_xl8: {value: 'padding-left: var(--space_xl8);'},
	pl_xl9: {value: 'padding-left: var(--space_xl9);'},
	pl_xl10: {value: 'padding-left: var(--space_xl10);'},
	pl_xl11: {value: 'padding-left: var(--space_xl11);'},
	pl_xl12: {value: 'padding-left: var(--space_xl12);'},
	pl_xl13: {value: 'padding-left: var(--space_xl13);'},
	pl_xl14: {value: 'padding-left: var(--space_xl14);'},
	pl_xl15: {value: 'padding-left: var(--space_xl15);'},
	px_0: {value: 'padding-left: 0;	padding-right: 0;'},
	px_xs5: {value: 'padding-left: var(--space_xs5);	padding-right: var(--space_xs5);'},
	px_xs4: {value: 'padding-left: var(--space_xs4);	padding-right: var(--space_xs4);'},
	px_xs3: {value: 'padding-left: var(--space_xs3);	padding-right: var(--space_xs3);'},
	px_xs2: {value: 'padding-left: var(--space_xs2);	padding-right: var(--space_xs2);'},
	px_xs: {value: 'padding-left: var(--space_xs);	padding-right: var(--space_xs);'},
	px_sm: {value: 'padding-left: var(--space_sm);	padding-right: var(--space_sm);'},
	px_md: {value: 'padding-left: var(--space_md);	padding-right: var(--space_md);'},
	px_lg: {value: 'padding-left: var(--space_lg);	padding-right: var(--space_lg);'},
	px_xl: {value: 'padding-left: var(--space_xl);	padding-right: var(--space_xl);'},
	px_xl2: {value: 'padding-left: var(--space_xl2);	padding-right: var(--space_xl2);'},
	px_xl3: {value: 'padding-left: var(--space_xl3);	padding-right: var(--space_xl3);'},
	px_xl4: {value: 'padding-left: var(--space_xl4);	padding-right: var(--space_xl4);'},
	px_xl5: {value: 'padding-left: var(--space_xl5);	padding-right: var(--space_xl5);'},
	px_xl6: {value: 'padding-left: var(--space_xl6);	padding-right: var(--space_xl6);'},
	px_xl7: {value: 'padding-left: var(--space_xl7);	padding-right: var(--space_xl7);'},
	px_xl8: {value: 'padding-left: var(--space_xl8);	padding-right: var(--space_xl8);'},
	px_xl9: {value: 'padding-left: var(--space_xl9);	padding-right: var(--space_xl9);'},
	px_xl10: {value: 'padding-left: var(--space_xl10);	padding-right: var(--space_xl10);'},
	px_xl11: {value: 'padding-left: var(--space_xl11);	padding-right: var(--space_xl11);'},
	px_xl12: {value: 'padding-left: var(--space_xl12);	padding-right: var(--space_xl12);'},
	px_xl13: {value: 'padding-left: var(--space_xl13);	padding-right: var(--space_xl13);'},
	px_xl14: {value: 'padding-left: var(--space_xl14);	padding-right: var(--space_xl14);'},
	px_xl15: {value: 'padding-left: var(--space_xl15);	padding-right: var(--space_xl15);'},
	py_0: {value: 'padding-top: 0;	padding-bottom: 0;'},
	py_xs5: {value: 'padding-top: var(--space_xs5);	padding-bottom: var(--space_xs5);'},
	py_xs4: {value: 'padding-top: var(--space_xs4);	padding-bottom: var(--space_xs4);'},
	py_xs3: {value: 'padding-top: var(--space_xs3);	padding-bottom: var(--space_xs3);'},
	py_xs2: {value: 'padding-top: var(--space_xs2);	padding-bottom: var(--space_xs2);'},
	py_xs: {value: 'padding-top: var(--space_xs);	padding-bottom: var(--space_xs);'},
	py_sm: {value: 'padding-top: var(--space_sm);	padding-bottom: var(--space_sm);'},
	py_md: {value: 'padding-top: var(--space_md);	padding-bottom: var(--space_md);'},
	py_lg: {value: 'padding-top: var(--space_lg);	padding-bottom: var(--space_lg);'},
	py_xl: {value: 'padding-top: var(--space_xl);	padding-bottom: var(--space_xl);'},
	py_xl2: {value: 'padding-top: var(--space_xl2);	padding-bottom: var(--space_xl2);'},
	py_xl3: {value: 'padding-top: var(--space_xl3);	padding-bottom: var(--space_xl3);'},
	py_xl4: {value: 'padding-top: var(--space_xl4);	padding-bottom: var(--space_xl4);'},
	py_xl5: {value: 'padding-top: var(--space_xl5);	padding-bottom: var(--space_xl5);'},
	py_xl6: {value: 'padding-top: var(--space_xl6);	padding-bottom: var(--space_xl6);'},
	py_xl7: {value: 'padding-top: var(--space_xl7);	padding-bottom: var(--space_xl7);'},
	py_xl8: {value: 'padding-top: var(--space_xl8);	padding-bottom: var(--space_xl8);'},
	py_xl9: {value: 'padding-top: var(--space_xl9);	padding-bottom: var(--space_xl9);'},
	py_xl10: {value: 'padding-top: var(--space_xl10);	padding-bottom: var(--space_xl10);'},
	py_xl11: {value: 'padding-top: var(--space_xl11);	padding-bottom: var(--space_xl11);'},
	py_xl12: {value: 'padding-top: var(--space_xl12);	padding-bottom: var(--space_xl12);'},
	py_xl13: {value: 'padding-top: var(--space_xl13);	padding-bottom: var(--space_xl13);'},
	py_xl14: {value: 'padding-top: var(--space_xl14);	padding-bottom: var(--space_xl14);'},
	py_xl15: {value: 'padding-top: var(--space_xl15);	padding-bottom: var(--space_xl15);'},
	m_0: {value: 'margin: 0;'},
	m_auto: {value: 'margin: auto;'},
	m_xs5: {value: 'margin: var(--space_xs5);'},
	m_xs4: {value: 'margin: var(--space_xs4);'},
	m_xs3: {value: 'margin: var(--space_xs3);'},
	m_xs2: {value: 'margin: var(--space_xs2);'},
	m_xs: {value: 'margin: var(--space_xs);'},
	m_sm: {value: 'margin: var(--space_sm);'},
	m_md: {value: 'margin: var(--space_md);'},
	m_lg: {value: 'margin: var(--space_lg);'},
	m_xl: {value: 'margin: var(--space_xl);'},
	m_xl2: {value: 'margin: var(--space_xl2);'},
	m_xl3: {value: 'margin: var(--space_xl3);'},
	m_xl4: {value: 'margin: var(--space_xl4);'},
	m_xl5: {value: 'margin: var(--space_xl5);'},
	m_xl6: {value: 'margin: var(--space_xl6);'},
	m_xl7: {value: 'margin: var(--space_xl7);'},
	m_xl8: {value: 'margin: var(--space_xl8);'},
	m_xl9: {value: 'margin: var(--space_xl9);'},
	m_xl10: {value: 'margin: var(--space_xl10);'},
	m_xl11: {value: 'margin: var(--space_xl11);'},
	m_xl12: {value: 'margin: var(--space_xl12);'},
	m_xl13: {value: 'margin: var(--space_xl13);'},
	m_xl14: {value: 'margin: var(--space_xl14);'},
	m_xl15: {value: 'margin: var(--space_xl15);'},
	mt_0: {value: 'margin-top: 0;'},
	mt_auto: {value: 'margin-top: auto;'},
	mt_xs5: {value: 'margin-top: var(--space_xs5);'},
	mt_xs4: {value: 'margin-top: var(--space_xs4);'},
	mt_xs3: {value: 'margin-top: var(--space_xs3);'},
	mt_xs2: {value: 'margin-top: var(--space_xs2);'},
	mt_xs: {value: 'margin-top: var(--space_xs);'},
	mt_sm: {value: 'margin-top: var(--space_sm);'},
	mt_md: {value: 'margin-top: var(--space_md);'},
	mt_lg: {value: 'margin-top: var(--space_lg);'},
	mt_xl: {value: 'margin-top: var(--space_xl);'},
	mt_xl2: {value: 'margin-top: var(--space_xl2);'},
	mt_xl3: {value: 'margin-top: var(--space_xl3);'},
	mt_xl4: {value: 'margin-top: var(--space_xl4);'},
	mt_xl5: {value: 'margin-top: var(--space_xl5);'},
	mt_xl6: {value: 'margin-top: var(--space_xl6);'},
	mt_xl7: {value: 'margin-top: var(--space_xl7);'},
	mt_xl8: {value: 'margin-top: var(--space_xl8);'},
	mt_xl9: {value: 'margin-top: var(--space_xl9);'},
	mt_xl10: {value: 'margin-top: var(--space_xl10);'},
	mt_xl11: {value: 'margin-top: var(--space_xl11);'},
	mt_xl12: {value: 'margin-top: var(--space_xl12);'},
	mt_xl13: {value: 'margin-top: var(--space_xl13);'},
	mt_xl14: {value: 'margin-top: var(--space_xl14);'},
	mt_xl15: {value: 'margin-top: var(--space_xl15);'},
	mr_0: {value: 'margin-right: 0;'},
	mr_auto: {value: 'margin-right: auto;'},
	mr_xs5: {value: 'margin-right: var(--space_xs5);'},
	mr_xs4: {value: 'margin-right: var(--space_xs4);'},
	mr_xs3: {value: 'margin-right: var(--space_xs3);'},
	mr_xs2: {value: 'margin-right: var(--space_xs2);'},
	mr_xs: {value: 'margin-right: var(--space_xs);'},
	mr_sm: {value: 'margin-right: var(--space_sm);'},
	mr_md: {value: 'margin-right: var(--space_md);'},
	mr_lg: {value: 'margin-right: var(--space_lg);'},
	mr_xl: {value: 'margin-right: var(--space_xl);'},
	mr_xl2: {value: 'margin-right: var(--space_xl2);'},
	mr_xl3: {value: 'margin-right: var(--space_xl3);'},
	mr_xl4: {value: 'margin-right: var(--space_xl4);'},
	mr_xl5: {value: 'margin-right: var(--space_xl5);'},
	mr_xl6: {value: 'margin-right: var(--space_xl6);'},
	mr_xl7: {value: 'margin-right: var(--space_xl7);'},
	mr_xl8: {value: 'margin-right: var(--space_xl8);'},
	mr_xl9: {value: 'margin-right: var(--space_xl9);'},
	mr_xl10: {value: 'margin-right: var(--space_xl10);'},
	mr_xl11: {value: 'margin-right: var(--space_xl11);'},
	mr_xl12: {value: 'margin-right: var(--space_xl12);'},
	mr_xl13: {value: 'margin-right: var(--space_xl13);'},
	mr_xl14: {value: 'margin-right: var(--space_xl14);'},
	mr_xl15: {value: 'margin-right: var(--space_xl15);'},
	mb_0: {value: 'margin-bottom: 0;'},
	mb_auto: {value: 'margin-bottom: auto;'},
	mb_xs5: {value: 'margin-bottom: var(--space_xs5);'},
	mb_xs4: {value: 'margin-bottom: var(--space_xs4);'},
	mb_xs3: {value: 'margin-bottom: var(--space_xs3);'},
	mb_xs2: {value: 'margin-bottom: var(--space_xs2);'},
	mb_xs: {value: 'margin-bottom: var(--space_xs);'},
	mb_sm: {value: 'margin-bottom: var(--space_sm);'},
	mb_md: {value: 'margin-bottom: var(--space_md);'},
	mb_lg: {value: 'margin-bottom: var(--space_lg);'},
	mb_xl: {value: 'margin-bottom: var(--space_xl);'},
	mb_xl2: {value: 'margin-bottom: var(--space_xl2);'},
	mb_xl3: {value: 'margin-bottom: var(--space_xl3);'},
	mb_xl4: {value: 'margin-bottom: var(--space_xl4);'},
	mb_xl5: {value: 'margin-bottom: var(--space_xl5);'},
	mb_xl6: {value: 'margin-bottom: var(--space_xl6);'},
	mb_xl7: {value: 'margin-bottom: var(--space_xl7);'},
	mb_xl8: {value: 'margin-bottom: var(--space_xl8);'},
	mb_xl9: {value: 'margin-bottom: var(--space_xl9);'},
	mb_xl10: {value: 'margin-bottom: var(--space_xl10);'},
	mb_xl11: {value: 'margin-bottom: var(--space_xl11);'},
	mb_xl12: {value: 'margin-bottom: var(--space_xl12);'},
	mb_xl13: {value: 'margin-bottom: var(--space_xl13);'},
	mb_xl14: {value: 'margin-bottom: var(--space_xl14);'},
	mb_xl15: {value: 'margin-bottom: var(--space_xl15);'},
	ml_0: {value: 'margin-left: 0;'},
	ml_auto: {value: 'margin-left: auto;'},
	ml_xs5: {value: 'margin-left: var(--space_xs5);'},
	ml_xs4: {value: 'margin-left: var(--space_xs4);'},
	ml_xs3: {value: 'margin-left: var(--space_xs3);'},
	ml_xs2: {value: 'margin-left: var(--space_xs2);'},
	ml_xs: {value: 'margin-left: var(--space_xs);'},
	ml_sm: {value: 'margin-left: var(--space_sm);'},
	ml_md: {value: 'margin-left: var(--space_md);'},
	ml_lg: {value: 'margin-left: var(--space_lg);'},
	ml_xl: {value: 'margin-left: var(--space_xl);'},
	ml_xl2: {value: 'margin-left: var(--space_xl2);'},
	ml_xl3: {value: 'margin-left: var(--space_xl3);'},
	ml_xl4: {value: 'margin-left: var(--space_xl4);'},
	ml_xl5: {value: 'margin-left: var(--space_xl5);'},
	ml_xl6: {value: 'margin-left: var(--space_xl6);'},
	ml_xl7: {value: 'margin-left: var(--space_xl7);'},
	ml_xl8: {value: 'margin-left: var(--space_xl8);'},
	ml_xl9: {value: 'margin-left: var(--space_xl9);'},
	ml_xl10: {value: 'margin-left: var(--space_xl10);'},
	ml_xl11: {value: 'margin-left: var(--space_xl11);'},
	ml_xl12: {value: 'margin-left: var(--space_xl12);'},
	ml_xl13: {value: 'margin-left: var(--space_xl13);'},
	ml_xl14: {value: 'margin-left: var(--space_xl14);'},
	ml_xl15: {value: 'margin-left: var(--space_xl15);'},
	mx_0: {value: 'margin-left: 0;	margin-right: 0;'},
	mx_auto: {value: 'margin-left: auto;	margin-right: auto;'},
	mx_xs5: {value: 'margin-left: var(--space_xs5);	margin-right: var(--space_xs5);'},
	mx_xs4: {value: 'margin-left: var(--space_xs4);	margin-right: var(--space_xs4);'},
	mx_xs3: {value: 'margin-left: var(--space_xs3);	margin-right: var(--space_xs3);'},
	mx_xs2: {value: 'margin-left: var(--space_xs2);	margin-right: var(--space_xs2);'},
	mx_xs: {value: 'margin-left: var(--space_xs);	margin-right: var(--space_xs);'},
	mx_sm: {value: 'margin-left: var(--space_sm);	margin-right: var(--space_sm);'},
	mx_md: {value: 'margin-left: var(--space_md);	margin-right: var(--space_md);'},
	mx_lg: {value: 'margin-left: var(--space_lg);	margin-right: var(--space_lg);'},
	mx_xl: {value: 'margin-left: var(--space_xl);	margin-right: var(--space_xl);'},
	mx_xl2: {value: 'margin-left: var(--space_xl2);	margin-right: var(--space_xl2);'},
	mx_xl3: {value: 'margin-left: var(--space_xl3);	margin-right: var(--space_xl3);'},
	mx_xl4: {value: 'margin-left: var(--space_xl4);	margin-right: var(--space_xl4);'},
	mx_xl5: {value: 'margin-left: var(--space_xl5);	margin-right: var(--space_xl5);'},
	mx_xl6: {value: 'margin-left: var(--space_xl6);	margin-right: var(--space_xl6);'},
	mx_xl7: {value: 'margin-left: var(--space_xl7);	margin-right: var(--space_xl7);'},
	mx_xl8: {value: 'margin-left: var(--space_xl8);	margin-right: var(--space_xl8);'},
	mx_xl9: {value: 'margin-left: var(--space_xl9);	margin-right: var(--space_xl9);'},
	mx_xl10: {value: 'margin-left: var(--space_xl10);	margin-right: var(--space_xl10);'},
	mx_xl11: {value: 'margin-left: var(--space_xl11);	margin-right: var(--space_xl11);'},
	mx_xl12: {value: 'margin-left: var(--space_xl12);	margin-right: var(--space_xl12);'},
	mx_xl13: {value: 'margin-left: var(--space_xl13);	margin-right: var(--space_xl13);'},
	mx_xl14: {value: 'margin-left: var(--space_xl14);	margin-right: var(--space_xl14);'},
	mx_xl15: {value: 'margin-left: var(--space_xl15);	margin-right: var(--space_xl15);'},
	my_0: {value: 'margin-top: 0;	margin-bottom: 0;'},
	my_auto: {value: 'margin-top: auto;	margin-bottom: auto;'},
	my_xs5: {value: 'margin-top: var(--space_xs5);	margin-bottom: var(--space_xs5);'},
	my_xs4: {value: 'margin-top: var(--space_xs4);	margin-bottom: var(--space_xs4);'},
	my_xs3: {value: 'margin-top: var(--space_xs3);	margin-bottom: var(--space_xs3);'},
	my_xs2: {value: 'margin-top: var(--space_xs2);	margin-bottom: var(--space_xs2);'},
	my_xs: {value: 'margin-top: var(--space_xs);	margin-bottom: var(--space_xs);'},
	my_sm: {value: 'margin-top: var(--space_sm);	margin-bottom: var(--space_sm);'},
	my_md: {value: 'margin-top: var(--space_md);	margin-bottom: var(--space_md);'},
	my_lg: {value: 'margin-top: var(--space_lg);	margin-bottom: var(--space_lg);'},
	my_xl: {value: 'margin-top: var(--space_xl);	margin-bottom: var(--space_xl);'},
	my_xl2: {value: 'margin-top: var(--space_xl2);	margin-bottom: var(--space_xl2);'},
	my_xl3: {value: 'margin-top: var(--space_xl3);	margin-bottom: var(--space_xl3);'},
	my_xl4: {value: 'margin-top: var(--space_xl4);	margin-bottom: var(--space_xl4);'},
	my_xl5: {value: 'margin-top: var(--space_xl5);	margin-bottom: var(--space_xl5);'},
	my_xl6: {value: 'margin-top: var(--space_xl6);	margin-bottom: var(--space_xl6);'},
	my_xl7: {value: 'margin-top: var(--space_xl7);	margin-bottom: var(--space_xl7);'},
	my_xl8: {value: 'margin-top: var(--space_xl8);	margin-bottom: var(--space_xl8);'},
	my_xl9: {value: 'margin-top: var(--space_xl9);	margin-bottom: var(--space_xl9);'},
	my_xl10: {value: 'margin-top: var(--space_xl10);	margin-bottom: var(--space_xl10);'},
	my_xl11: {value: 'margin-top: var(--space_xl11);	margin-bottom: var(--space_xl11);'},
	my_xl12: {value: 'margin-top: var(--space_xl12);	margin-bottom: var(--space_xl12);'},
	my_xl13: {value: 'margin-top: var(--space_xl13);	margin-bottom: var(--space_xl13);'},
	my_xl14: {value: 'margin-top: var(--space_xl14);	margin-bottom: var(--space_xl14);'},
	my_xl15: {value: 'margin-top: var(--space_xl15);	margin-bottom: var(--space_xl15);'},
	gap_xs5: {value: 'gap: var(--space_xs5);'},
	gap_xs4: {value: 'gap: var(--space_xs4);'},
	gap_xs3: {value: 'gap: var(--space_xs3);'},
	gap_xs2: {value: 'gap: var(--space_xs2);'},
	gap_xs: {value: 'gap: var(--space_xs);'},
	gap_sm: {value: 'gap: var(--space_sm);'},
	gap_md: {value: 'gap: var(--space_md);'},
	gap_lg: {value: 'gap: var(--space_lg);'},
	gap_xl: {value: 'gap: var(--space_xl);'},
	gap_xl2: {value: 'gap: var(--space_xl2);'},
	gap_xl3: {value: 'gap: var(--space_xl3);'},
	gap_xl4: {value: 'gap: var(--space_xl4);'},
	gap_xl5: {value: 'gap: var(--space_xl5);'},
	gap_xl6: {value: 'gap: var(--space_xl6);'},
	gap_xl7: {value: 'gap: var(--space_xl7);'},
	gap_xl8: {value: 'gap: var(--space_xl8);'},
	gap_xl9: {value: 'gap: var(--space_xl9);'},
	gap_xl10: {value: 'gap: var(--space_xl10);'},
	gap_xl11: {value: 'gap: var(--space_xl11);'},
	gap_xl12: {value: 'gap: var(--space_xl12);'},
	gap_xl13: {value: 'gap: var(--space_xl13);'},
	gap_xl14: {value: 'gap: var(--space_xl14);'},
	gap_xl15: {value: 'gap: var(--space_xl15);'},
	column_gap_xs5: {value: 'column-gap: var(--space_xs5);'},
	column_gap_xs4: {value: 'column-gap: var(--space_xs4);'},
	column_gap_xs3: {value: 'column-gap: var(--space_xs3);'},
	column_gap_xs2: {value: 'column-gap: var(--space_xs2);'},
	column_gap_xs: {value: 'column-gap: var(--space_xs);'},
	column_gap_sm: {value: 'column-gap: var(--space_sm);'},
	column_gap_md: {value: 'column-gap: var(--space_md);'},
	column_gap_lg: {value: 'column-gap: var(--space_lg);'},
	column_gap_xl: {value: 'column-gap: var(--space_xl);'},
	column_gap_xl2: {value: 'column-gap: var(--space_xl2);'},
	column_gap_xl3: {value: 'column-gap: var(--space_xl3);'},
	column_gap_xl4: {value: 'column-gap: var(--space_xl4);'},
	column_gap_xl5: {value: 'column-gap: var(--space_xl5);'},
	column_gap_xl6: {value: 'column-gap: var(--space_xl6);'},
	column_gap_xl7: {value: 'column-gap: var(--space_xl7);'},
	column_gap_xl8: {value: 'column-gap: var(--space_xl8);'},
	column_gap_xl9: {value: 'column-gap: var(--space_xl9);'},
	column_gap_xl10: {value: 'column-gap: var(--space_xl10);'},
	column_gap_xl11: {value: 'column-gap: var(--space_xl11);'},
	column_gap_xl12: {value: 'column-gap: var(--space_xl12);'},
	column_gap_xl13: {value: 'column-gap: var(--space_xl13);'},
	column_gap_xl14: {value: 'column-gap: var(--space_xl14);'},
	column_gap_xl15: {value: 'column-gap: var(--space_xl15);'},
	row_gap_xs5: {value: 'row-gap: var(--space_xs5);'},
	row_gap_xs4: {value: 'row-gap: var(--space_xs4);'},
	row_gap_xs3: {value: 'row-gap: var(--space_xs3);'},
	row_gap_xs2: {value: 'row-gap: var(--space_xs2);'},
	row_gap_xs: {value: 'row-gap: var(--space_xs);'},
	row_gap_sm: {value: 'row-gap: var(--space_sm);'},
	row_gap_md: {value: 'row-gap: var(--space_md);'},
	row_gap_lg: {value: 'row-gap: var(--space_lg);'},
	row_gap_xl: {value: 'row-gap: var(--space_xl);'},
	row_gap_xl2: {value: 'row-gap: var(--space_xl2);'},
	row_gap_xl3: {value: 'row-gap: var(--space_xl3);'},
	row_gap_xl4: {value: 'row-gap: var(--space_xl4);'},
	row_gap_xl5: {value: 'row-gap: var(--space_xl5);'},
	row_gap_xl6: {value: 'row-gap: var(--space_xl6);'},
	row_gap_xl7: {value: 'row-gap: var(--space_xl7);'},
	row_gap_xl8: {value: 'row-gap: var(--space_xl8);'},
	row_gap_xl9: {value: 'row-gap: var(--space_xl9);'},
	row_gap_xl10: {value: 'row-gap: var(--space_xl10);'},
	row_gap_xl11: {value: 'row-gap: var(--space_xl11);'},
	row_gap_xl12: {value: 'row-gap: var(--space_xl12);'},
	row_gap_xl13: {value: 'row-gap: var(--space_xl13);'},
	row_gap_xl14: {value: 'row-gap: var(--space_xl14);'},
	row_gap_xl15: {value: 'row-gap: var(--space_xl15);'},
};
