import type {Gen} from '@ryanatkn/gro';
import {to_root_path} from '@ryanatkn/gro/paths.js';
import {readFile} from 'node:fs/promises';

/**
 * Concatenates the `.css` files into `style.css` as a convenience.
 */
export const gen: Gen = async ({origin_id}) => {
	const banner = `/* generated by ${to_root_path(origin_id)} */`;

	// The style utilities override everything else, so they go last,
	// and some selectors in previous files may need to lower specificity with `:where`.

	const sheets = await Promise.all([
		concat_stylesheet('./src/lib/style_reset.css'),

		concat_stylesheet('./src/lib/style_components.css'),

		concat_stylesheet('./src/lib/style_animations.css'),

		concat_stylesheet('./src/lib/style_utilities.css'),
	]);

	return `${banner}

${sheets.join('\n\n')}

    ${banner}
  `;
};

const concat_stylesheet = async (path: string): Promise<string> => {
	const contents = await readFile(path, 'utf8');

	return `
/* @source ${path} */

${contents}

/* end ${path} */\n\n`;
};
