import type {Gen} from '@ryanatkn/gro';
import {to_root_path} from '@ryanatkn/gro/paths.js';
import {readFile} from 'node:fs/promises';

/**
 * Concatenates the `.css` files into `style.css` as a convenience.
 */
export const gen: Gen = async ({origin_id}) => {
	const banner = `/* generated by ${to_root_path(origin_id)} */`;

	// The style utilities override everything else, so they go last,
	// and some selectors in previous files may need to lower specificity with `:where`.
	return `${banner}

${await readFile('./src/lib/style_reset.css', 'utf8')}

${await readFile('./src/lib/style_components.css', 'utf8')}

${await readFile('./src/lib/style_animations.css', 'utf8')}

${await readFile('./src/lib/style_utilities.css', 'utf8')}

    ${banner}
  `;
};
