import type {Gen} from '@ryanatkn/gro';
import {to_root_path} from '@ryanatkn/gro/paths.js';

import {default_themes} from '$lib/themes.js';
import {render_theme_style} from '$lib/theme.js';

// TODO maybe this should be `base_theme.css` or `base.css` or something,
// and we could also generate and publish the other themes --
// that would allow them to be staticly used,
// currently you'd have to pass a dynamic `theme` to `Themed`
export const gen: Gen = async ({origin_id}) => {
	const banner = `/* generated by ${to_root_path(origin_id)} */`;

	const theme = default_themes[0];
	const theme_style = render_theme_style(theme, {
		comments: true,
		empty_default_theme: false,
		specificity: 1,
	});

	return `${banner}

		/* theme: ${theme.name} */
    ${theme_style}

    ${banner}
  `;
};
