<script lang="ts">
	import Tome_Content from '@ryanatkn/fuz/Tome_Content.svelte';
	import Mdn_Link from '@ryanatkn/fuz/Mdn_Link.svelte';
	import {get_tome_by_name} from '@ryanatkn/fuz/tome.js';

	import Module_Link from '$routes/Module_Link.svelte';
	import Introduction from '$routes/Introduction.svelte';

	const LIBRARY_ITEM_NAME = 'introduction';

	const tome = get_tome_by_name(LIBRARY_ITEM_NAME);
</script>

<Tome_Content {tome}>
	<section>
		<Introduction />
		<p>Details:</p>
		<ul>
			<li>plain CSS</li>
			<li>zero dependencies</li>
			<li>exports one main stylesheet that doubles as a reset with basic HTML tag styles</li>
			<li>exports a basic theme that can be replaced with your own</li>
			<li>
				also exports the underlying CSS data, helpers, and types, which can be used in many ways,
				including outputting an optimized utilities class file
			</li>
			<li>
				uses its own concept of style variables, a specialization of CSS custom properties and
				design tokens
				<ul>
					<li>variables are the main source of truth</li>
					<li>each variable provides values to light and/or dark mode</li>
					<li>includes optional utility and component classes that use the variables</li>
				</ul>
			</li>
			<li>themes are groups of variables</li>
			<li>
				dark mode is a first-class concept in the system, not a theme, instead each theme can
				support light and/or dark <Mdn_Link path="Web/CSS/color-scheme">color-schemes</Mdn_Link>
			</li>
			<li>
				is agnostic to JS frameworks, for example usage see <a
					href="https://www.fuz.dev/docs/Themed"><code>Themed</code></a
				>
				in my Svelte UI library <a href="https://www.fuz.dev/">Fuz</a>
			</li>
		</ul>
		<p>The stylesheets:</p>
		<ul>
			<li>
				<Module_Link path="style.css" /> - the main stylesheet and CSS reset
			</li>
			<li>
				<Module_Link path="theme.css" /> - or bring your own
			</li>
			<li>
				<Module_Link
					path="moss.css"
					base_path="https://github.com/ryanatkn/moss/blob/main/src/routes/"
					>$routes/moss.css</Module_Link
				> - a reference implementation using Moss's helpers that includes only the utility classes your
				code uses, generated by
				<a href="https://github.com/ryanatkn/gro">Gro</a> with the Moss helpers in
				<Module_Link path="gen_moss_css.js" />.
			</li>
			<li>
				There are no tools yet for optimizing away unused variables, so <code>style.css</code> and
				<code>theme.css</code> have some bloat.
			</li>
		</ul>
		<p>
			Moss is being made to support <a href="https://www.zzz.software/">Zzz</a> and
			<a href="https://www.ryanatkn.com/">my other projects</a> that focus on end-users, so it'll grow
			relatively slowly as I encounter more usecases. It's hobby-ready but expect a lot of breaking changes.
			Feel free to take the code and ideas for your own purposes.
		</p>
		<p>
			In the docs, you'll see I'm writing asides using "⚠️" with open questions and other discussion
			of uncertainties. Your input is appreciated in the GitHub
			<a href="https://github.com/ryanatkn/moss/issues">issues</a> and
			<a href="https://github.com/ryanatkn/moss/discussions">discussions</a>, or find me on
			<a href="https://bsky.app/profile/ryanatkn.com">Bluesky</a>. See
			<a href="https://github.com/ryanatkn/moss/blob/main/contributing.md">contributing.md</a> for more
			🌿
		</p>
	</section>
</Tome_Content>
